[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
buildTextureFeature = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss04"

    [buildPlans.iosevka-custom.variants.design]
    at = "fourfold"
    dollar = "open"
    cent = "open"
    l = "zshaped"

  [buildPlans.iosevka-custom.ligations]
  inherits = "fsharp"
  disables = ["ltgt-ne"]
  enables = ["llgg", "brack-bar", "brace-bar"]
