[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
build-texture-feature = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss04"

    [buildPlans.iosevka-custom.variants.design]
    at = "fourfold"
    dollar = "open"
    cent = "open"
    l = "zshaped"

  [buildPlans.iosevka-custom.ligations]
  inherits = "fsharp"
  disables = ["ltgt-ne"]
  enables = ["llgg", "brack-bar"]
